Feature/interest
TrioBrothers/mk_hotblood pull request #6
Opened 2021-01-26 02:27 UTC by minkyuChung

계좌의 종류가 보통예금계좌와 신용신뢰계좌로 구분되도록 기능을 추가하였습니다.

보통예금계좌(NormalAccount 클래스)
- 계좌 생성시 입력한 이자율을 적용하여 입금됩니다.

신용신뢰계좌(HighCreditAccount 클래스)
- 신용등급에 따른 이자율을 추가 적용하여 입금됩니다.

새로운 기능에 따른 기존 클래스들의 변경이 있었습니다. 
- 계좌 생성 메뉴에서 계좌 종류 선택 기능 추가
- 입금 시 잔액 업데이트 방식 변경

2021-01-26 05:30 UTC, planepaper requested changes

2021-01-26 05:30 UTC, planepaper commented on Project1/AccountHandler.cpp
> +	}
### sel의 경우를 더 구체적으로 나눠주라
sel이 2인 경우에만 현재 명시가 되어있는데,
sel이 1인 경우에도 어떤 동작을 하는지 코드상으로 보여주면 좋을거같네.

`switch 문`으로 하는 방법 혹은 
지금처럼 if(sel==1), else if(sel ==2 ) `if else문` 을 이용해도되고
물론 예외사항도 처리를 해줘야겠지? 3 따위를 입력했을 때 재입력을 받게해야할거같네.

너도 궁금해하는 사실이겠지만, sel ==1 를 추가하면 cout과 cin코드를 중복되서 1인경우, 2인경우에 적어줘야하겠지?
그래서 저 내용을 함수로 만들어서 받게하는게 좋을거같아. 구조체를 만들어서 return 형식이 해당 구조체인 함수를 만들면 되겠지?

힌트를 주자면
```cpp
struct AccountInfo 
{
  int idNum;
  char name[MAX_LEGNTH];
  int bal;
}

AccountInfo EnterAccountInfo()
{
  AccountInfo accInfo;
  cin >> accInfo.idNum;
  return accInfo;
}

```

### return 문을 여러개 쓰는 것은 지양해보자
마지막으로 함수 끝에 오는 return 말고의 return 문을 만드는건 웬만해서는 지양하는게 좋아.
물론 그렇게쓰는게 좋은 코드 일 때도 있는데, 지양해서 써보려고 노력하는게 좋을거같네 :)

2021-01-27 01:51 UTC, minkyuChung commented on Project1/AccountHandler.cpp
> +	}
수정한 사항 확인해주세요~

2021-01-27 10:51 UTC, planepaper commented on Project1/AccountHandler.cpp
> +	}
### 미팅 때 얘기할 것
생성자 매개변수 AccountInfo로 바꾸기

2021-02-02 06:32 UTC, minkyuChung commented on Project1/AccountHandler.cpp
> +	}
생성자 매개변수 변경했습니다 확인부탁드려요

2021-02-02 07:03 UTC, planepaper requested changes

2021-02-02 07:03 UTC, planepaper commented on Project1/AccountHandler.h
> +//};
코드를 주석으로해서 올리는건 지양하는게 좋아!

만약에 주석으로 올려야만하는 경우에는, 왜 주석으로 올리게됐는지 그 내용을 주석 주변에 달아주는게 좋아 :)

그런데 여기 주석 코드는 AccountInfo 가 딴데로 옮겨졌으니 필요 없어보이네
삭제하는게 좋을거같다 :)

2021-02-02 07:03 UTC, planepaper commented on Project1/NormalAccount.h
> +	int interest;
AccountInfo 는 말그대로 Account 정보니까 Account.h 에 있는게 더 적합할거같다 ㅎㅎ

사실 저 구조체를 위 방법 말고도 다른 방법으로 위치시킬 수 있는데
1. Account.h에 선언하기
2. AcountInfo.h라는 헤더파일을 만들어서 안에 struct AccountInfo만 선언 뒤에 #include로 이용하기

1번이 제일 나아보인다. 어차피 구조체 내용이 많지 않으니 :)

2021-02-02 07:05 UTC, planepaper commented on Project1/NormalAccount.h
> +	int interest;
ㅋㅋ이거 인용한 코드, 내용이 좀 짤렸는데 잘 알아볼수있길..ㅎㅎ

2021-02-02 13:32 UTC, merged